name: Build ShopManager APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: shop_mobile
          buildozer_version: stable

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ShopManager-APK
          path: ${{ steps.buildozer.outputs.filename }}
          if-no-files-found: error
